// Inline the runtime dictionaries of locale/<id>.json into a TypeScript module.
//
// DSH reads a package's locale JSON only for display metadata (`meta.title` and
// `meta.description`); it never registers those files as runtime Client
// dictionaries. The Client half therefore has to register its own namespace,
// and this generator keeps locale/*.json as the single source of truth instead
// of duplicating the strings in TypeScript.
import { readFileSync, writeFileSync } from 'node:fs'

const namespace = 'dsh-remote-access'
const locales = ['en', 'zh']

const dictionaries = {}
for (const locale of locales) {
  const file = new URL(`../locale/${locale}.json`, import.meta.url)
  const parsed = JSON.parse(readFileSync(file, 'utf8'))
  const dict = parsed?.[namespace]
  if (dict === undefined || typeof dict !== 'object' || Array.isArray(dict)) {
    throw new Error(`locale/${locale}.json must declare the "${namespace}" namespace object`)
  }
  for (const [key, value] of Object.entries(dict)) {
    if (typeof value !== 'string') throw new Error(`locale/${locale}.json: ${namespace}.${key} must be a string`)
  }
  dictionaries[locale] = dict
}

const english = Object.keys(dictionaries.en)
for (const locale of locales) {
  const keys = Object.keys(dictionaries[locale])
  const missing = english.filter((key) => !keys.includes(key))
  const extra = keys.filter((key) => !english.includes(key))
  if (missing.length > 0 || extra.length > 0) {
    throw new Error(`locale/${locale}.json does not match locale/en.json (missing: ${missing.join(', ') || 'none'}; extra: ${extra.join(', ') || 'none'})`)
  }
}

const source = `// Generated by scripts/generate-locale.mjs from locale/*.json — do not edit by hand.
/** Client locale namespace owned by this plugin. */
export const localeNamespace = ${JSON.stringify(namespace)}

/** Runtime dictionaries keyed by DSH built-in locale id. */
export const dictionaries: Record<string, Record<string, string>> = ${JSON.stringify(dictionaries, null, 2)}
`

writeFileSync(new URL('../src/locale.generated.ts', import.meta.url), source)
console.log(`locale: inlined ${String(locales.length)} dictionaries (${String(english.length)} keys) into src/locale.generated.ts`)
